#!/usr/bin/env node

// usage: ./.travis/extract_json xxx.json
var fs = require('fs');
var path = require('path');
var filename = process.argv[2];
var courseDatas = JSON.parse(fs.readFileSync(filename, 'utf8'));

// filename looks like: 2016-1-ntust.json
var matchData = filename.match(/(\d+)\-(\d+)-(.+)\.json$/);

var year = matchData[1];
var term = matchData[2];
var school = matchData[3];

var rmdir = function(dir) {
	var list = fs.readdirSync(dir);
	for(var i = 0; i < list.length; i++) {
		var filename = path.join(dir, list[i]);
		var stat = fs.statSync(filename);

		if(filename == '.' || filename == '..') {
			// pass these files
		} else if(stat.isDirectory()) {
			// rmdir recursively
			rmdir(filename);
		} else {
			// rm fiilename
			fs.unlinkSync(filename);
		}
	}
	fs.rmdirSync(dir);
};

var directory = 'app/assets/data/' + year + '-' + term + '/' + school;
if (!fs.existsSync('app/assets/data/' + year + '-' + term)) { fs.mkdirSync('app/assets/data/' + year + '-' + term); }
if (fs.existsSync(directory)) { rmdir(directory); }

fs.mkdirSync(directory);
for (var data of courseDatas) {
  if (typeof data.code !== 'undefined' && data.code.length > 0) {
    fs.writeFileSync(directory + '/' + data.code + '.json', JSON.stringify(data));
  }
}

// Collection All classrooms
const classRoomSet = new Set();
let periodUsedClassroomsMap = {};
let classroomUsedTimeMap = {};

courseDatas.forEach(course => {
	course.periods.forEach(period => {
		classRoomSet.add(period.location);

		const dayAndTime = `${period.day} ${period.time}`;

		/* build periodUsedClassRoomsMap */
		if (typeof periodUsedClassroomsMap[dayAndTime] === 'undefined') {
			periodUsedClassroomsMap[dayAndTime] = new Set();
		}
		periodUsedClassroomsMap[dayAndTime].add(period.location);

		/* build classRoomUsedTimeMap */
		if (typeof classroomUsedTimeMap[period.location] === 'undefined') {
			classroomUsedTimeMap[period.location] = new Set();
		}
		classroomUsedTimeMap[period.location].add(dayAndTime);
	});
});

function convertSetMap(oldMap) {
	return Object.keys(oldMap).reduce((newMap, key) => {
		return Object.assign({}, newMap, {[key]: Array.from(oldMap[key])});
	}, {});
}

periodUsedClassroomsMap = convertSetMap(periodUsedClassroomsMap);
classroomUsedTimeMap = convertSetMap(classroomUsedTimeMap);
const classRooms = Array.from(classRoomSet);

fs.writeFileSync(path.join(directory, `../${school}-classrooms.json`), JSON.stringify(classRooms));
fs.writeFileSync(path.join(directory, `../${school}-period-classrooms.json`), JSON.stringify(periodUsedClassroomsMap));
fs.writeFileSync(path.join(directory, `../${school}-classroom-times.json`), JSON.stringify(periodUsedClassroomsMap));
